FROM ubuntu:22.04
LABEL maintainer = "jkennedy107@my.bcit.ca"
RUN apt-get update -y && \
apt-get install -y python3 python3-pip

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]